###
DELETE http://localhost:8081/deleteaccount HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhZjY0MWEwNTFmMThmMzgwMDJkYmY5IiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2NTYwNjI5MjMsImV4cCI6MTY1NjA4MDkyM30.MDZ5v1VRm6aMPEWHVxCcpBYelGyIiu6_Ns5VJtoSlek


{
    "id": "62b4e8bd2476dc956639a404"
}

###
POST http://localhost:8081/getusers HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhZjY0MWEwNTFmMThmMzgwMDJkYmY5IiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2NTU4ODQ0MzIsImV4cCI6MTY1NTkwMjQzMn0.K1IP3ZeTK7BRD7SOakEmT7Q0C8xz5Q3-qdF97l6l75c

###
POST http://localhost:8081/getpollsdesc HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhZjY0MWEwNTFmMThmMzgwMDJkYmY5IiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2NTYwMDY0MzgsImV4cCI6MTY1NjAyNDQzOH0.r5YKWYqkNAW6fFcykQ6IALwOBjrbh15QyhxWKXMX7y8