###
DELETE http://localhost:8081/deleteaccount HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhNWE5Y2JiOWU3YjU1ZTc4ZmM4YTczIiwiZW1haWwiOiJKb2huV2lja0BnbWFpbC5jb20iLCJpYXQiOjE2NTUwMzI1MjYsImV4cCI6MTY1NTA1MDUyNn0.CEol3kkL29c-SkbZo7Sx_TixVlavUgcTE7UpKxRSCD0


{
    "id": "62a5f75a9ff8840f3c35a57f"
}

###
POST http://localhost:8081/getusers HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhZjY0MWEwNTFmMThmMzgwMDJkYmY5IiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2NTU2NjE4MTAsImV4cCI6MTY1NTY3OTgxMH0.jhBe9AXO_rwZp47xSkOE1172OGnGYQcp6PrsEZXJh2I