###
PATCH http://localhost:8081/updateprofile HTTP/1.1
Authorization: 
Content-Type: application/json

{
    "firstname": "update", 
    "lastname": "profile", 
    "pseudo": "updateprofile",
    "email": "updateprofile@gmail.com", 
    "password": "password",
    "bio": "nouveau profile", 
    "img": "" 
}