POST http://localhost:8081/signUp HTTP/1.1
Content-Type: application/json

{
    "firstname": "Kawai",
    "lastname": "kiwi",
    "pseudo": "TheUndertaker",
    "email": "undertaker@gmail.com",
    "password": "Undertaker",
    "bio": "never die",
    "img": ""
}

###
POST http://localhost:8081/uLogin HTTP/1.1
Content-Type: application/json


{
    "email": "User@gmail.com",
    "password": "votaction"
}

###
POST http://localhost:8081/uLogout HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhNWE5Y2JiOWU3YjU1ZTc4ZmM4YTczIiwiZW1haWwiOiJKb2huV2lja0BnbWFpbC5jb20iLCJpYXQiOjE2NTUwMjc5MTEsImV4cCI6MTY1NTA0NTkxMX0.mJmpdDUcbg8u0MstEk8Jgu9xl7KICA9Wg_NV7bw_r5A