POST http://localhost:8081/signUp HTTP/1.1
Content-Type: application/json

{
    "firstname": "Johnny",
    "lastname": "Wicky",
    "pseudo": "RealJohnWick",
    "email": "Johnny@gmail.com",
    "password": "RainbowSixSiege",
    "bio": "Bang Bang",
    "img": ""
}

###
POST http://localhost:8081/login HTTP/1.1
Content-Type: application/json


{
    "email": "JohnWick@gmail.com",
    "password": "LeagueOfLegends"
}

###
POST http://localhost:8081/logout HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhNWE5Y2JiOWU3YjU1ZTc4ZmM4YTczIiwiZW1haWwiOiJKb2huV2lja0BnbWFpbC5jb20iLCJpYXQiOjE2NTUwMjc5MTEsImV4cCI6MTY1NTA0NTkxMX0.mJmpdDUcbg8u0MstEk8Jgu9xl7KICA9Wg_NV7bw_r5A